#!/bin/bash

# DESCRIPTION
# stop will terminate the IBController and Interactive Brokers TWS/Gateway

set -e
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Permission denied; please run as sudo or root";
    exit
fi

PIDS="$(pgrep -f "ib-tws")" 

if [ -z "$PIDS" ]; then
	echo "No processes to kill; IBController is not running";
	exit
fi

sudo kill -9 "$PIDS"
echo "IBController and TWS/Gateway has been stopped"



