#!/bin/bash

# DESCRIPTION
# stop will terminate the IBController and Interactive Brokers TWS/Gateway

set -e
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Permission denied; please run as sudo or root";
    exit
fi
pgrep -f "ib-tws" | sudo xargs kill -9




